#spring:
#  datasource:
##    driver-class-name: org.mariadb.jdbc.Driver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log 찍기 위한 driver class
##    url: jdbc:mariadb://localhost:3306
#    url: jdbc:log4jdbc:mariadb://localhost:3306/account_sys
#    username: admin
#    password: admin
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/accountDiary01?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: 0931

batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

mybatis:
  type-aliases-package: com.template.restapi.aggregate.**.domain.entity
  mapper-locations: classpath:mappers/*.xml
