#spring:
#  datasource:
##    driver-class-name: org.mariadb.jdbc.Driver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log 찍기 위한 driver class
##    url: jdbc:mariadb://localhost:3306
#    url: jdbc:log4jdbc:mariadb://localhost:3306/account_sys
#    username: admin
#    password: admin
spring:
    datasource:
#      driver-class-name: oracle.jdbc.driver.OracleDriver # log 찍기 위한 driver class
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/test_account
      username: admin
      password: admin

batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

mybatis:
  type-aliases-package: com.template.restapi.aggregate.**.domain.entity
  mapper-locations: classpath:mappers/*.xml
